/** Registro de iconos Lucide usados en la app (import explícito = tree-shakeable). */
import {
  LayoutGrid,
  Megaphone,
  CalendarDays,
  MessagesSquare,
  ClipboardList,
  FolderClosed,
  Bus,
  Users,
  Search,
  Bell,
  Plus,
  Heart,
  MessageCircle,
  MessageCircleOff,
  Bookmark,
  MoreHorizontal,
  ChevronDown,
  ChevronRight,
  ImageIcon,
  Trophy,
  Calendar,
  Paperclip,
  Send,
  Settings,
  LogOut,
  Pin,
  Sparkles,
  Globe,
  Check,
  CheckCheck,
  ChevronLeft,
  Image as ImageLucide,
  HeartHandshake,
  FileText,
  CreditCard,
  Upload,
  DoorOpen,
  CalendarX,
  CircleCheck,
  Clock,
  X,
  Inbox,
  Tag,
  ArrowRight,
  Star,
  Quote,
  Mail,
  Phone,
  MapPin,
  GraduationCap,
  ShieldCheck,
  Languages,
  Zap,
  Smile,
  Apple,
  Menu,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  Apple,
  Menu,
  LayoutGrid,
  Megaphone,
  CalendarDays,
  MessagesSquare,
  ClipboardList,
  FolderClosed,
  Bus,
  Users,
  Search,
  Bell,
  Plus,
  Heart,
  MessageCircle,
  MessageCircleOff,
  Bookmark,
  MoreHorizontal,
  ChevronDown,
  ChevronRight,
  ImageIcon,
  Trophy,
  Calendar,
  Paperclip,
  Send,
  Settings,
  LogOut,
  Pin,
  Sparkles,
  Globe,
  Check,
  CheckCheck,
  ChevronLeft,
  HeartHandshake,
  FileText,
  CreditCard,
  Upload,
  DoorOpen,
  CalendarX,
  CircleCheck,
  Clock,
  X,
  Inbox,
  Tag,
  ArrowRight,
  Star,
  Quote,
  Mail,
  Phone,
  MapPin,
  GraduationCap,
  ShieldCheck,
  Languages,
  Zap,
  Smile,
};

/** Iconos de portada de los posts (coverIcon → componente). */
export const COVER_ICONS: Record<string, LucideIcon> = {
  calendar: Calendar,
  megaphone: Megaphone,
  image: ImageLucide,
  trophy: Trophy,
  bus: Bus,
  heart: HeartHandshake,
};

export function Icon({
  name,
  className,
  strokeWidth,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name] ?? Megaphone;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden />;
}
